[package]
name = "gigr"
version = "0.1.0-alpha.1"
edition = "2024"

[dependencies]
rodio = "0.21.0"
ratatui = "0.29.0"
ratatui-image = "8.0.1"
image = "0.25.6"
color-eyre = "0.6.3"
crossterm = "0.28.1"